### ISSUE TITLE
Missing dependancies?

### ISSUE THREAD

**Issue by martinmchugh** [bacpop/PopPIPE#17]
I'm trying to run the updated transmission pipeline. I cloned the repository then installed dependancies based on install instructions and dependancies listed in environment.yml

`conda create -n poppipe-update snakemake pandas python numpy iqtree rapidnj ete3 ska pp-sketchlib poppunk r-fastbaps mandrake`

But this quickly fails at the ska_build step 

```
Traceback (most recent call last):
  File "/mnt/shared/scratch/mmchugh/private/poppipe-update/.snakemake/scripts/tmpfsyoy1hh.run_ska_build.py", line 10, in <module>
Traceback (most recent call last):
  File "/mnt/shared/scratch/mmchugh/private/poppipe-update/.snakemake/scripts/tmp3cko2sa4.run_ska_build.py", line 10, in <module>
Traceback (most recent call last):
  File "/mnt/shared/scratch/mmchugh/private/poppipe-update/.snakemake/scripts/tmpk6l4yu0r.run_ska_build.py", line 10, in <module>
Traceback (most recent call last):
  File "/mnt/shared/scratch/mmchugh/private/poppipe-update/.snakemake/scripts/tmpxzpqi69s.run_ska_build.py", line 10, in <module>
    subprocess.run(f"ska build -o {snakemake.params['skf_prefix']}" + \
  File "/mnt/shared/scratch/mmchugh/apps/conda/envs/poppipe-update/lib/python3.12/subprocess.py", line 571, in run
    subprocess.run(f"ska build -o {snakemake.params['skf_prefix']}" + \
  File "/mnt/shared/scratch/mmchugh/apps/conda/envs/poppipe-update/lib/python3.12/subprocess.py", line 571, in run
    subprocess.run(f"ska build -o {snakemake.params['skf_prefix']}" + \
  File "/mnt/shared/scratch/mmchugh/apps/conda/envs/poppipe-update/lib/python3.12/subprocess.py", line 571, in run
    subprocess.run(f"ska build -o {snakemake.params['skf_prefix']}" + \
  File "/mnt/shared/scratch/mmchugh/apps/conda/envs/poppipe-update/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ska build -o output/strains/1/split_kmers -f output/strains/1/rfile.txt -k 21 --min-qual 4 --min-count 20  --threads 1 -v 2> logs/ska_build_1.log' returned non-zero exit status 1.
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ska build -o output/strains/3/split_kmers -f output/strains/3/rfile.txt -k 21 --min-qual 4 --min-count 20  --threads 1 -v 2> logs/ska_build_3.log' returned non-zero exit status 1.
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ska build -o output/strains/2/split_kmers -f output/strains/2/rfile.txt -k 21 --min-qual 4 --min-count 20  --threads 1 -v 2> logs/ska_build_2.log' returned non-zero exit status 1.
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ska build -o output/strains/5/split_kmers -f output/strains/5/rfile.txt -k 21 --min-qual 4 --min-count 20  --threads 1 -v 2> logs/ska_build_5.log' returned non-zero exit status 1.
RuleException:
CalledProcessError in file /mnt/shared/scratch/mmchugh/private/poppipe-update/Snakefile, line 127:
Command 'set -euo pipefail;  /mnt/shared/scratch/mmchugh/apps/conda/envs/poppipe-update/bin/python3.12 /mnt/shared/scratch/mmchugh/private/poppipe-update/.snakemake/scripts/tmpk6l4yu0r.run_ska_build.py' returned non-zero exit status 1.
RuleException:
CalledProcessError in file /mnt/shared/scratch/mmchugh/private/poppipe-update/Snakefile, line 127:
Command 'set -euo pipefail;  /mnt/shared/scratch/mmchugh/apps/conda/envs/poppipe-update/bin/python3.12 /mnt/shared/scratch/mmchugh/private/poppipe-update/.snakemake/scripts/tmp3cko2sa4.run_ska_build.py' returned non-zero exit status 1.
RuleException:
CalledProcessError in file /mnt/shared/scratch/mmchugh/private/poppipe-update/Snakefile, line 127:
Command 'set -euo pipefail;  /mnt/shared/scratch/mmchugh/apps/conda/envs/poppipe-update/bin/python3.12 /mnt/shared/scratch/mmchugh/private/poppipe-update/.snakemake/scripts/tmpfsyoy1hh.run_ska_build.py' returned non-zero exit status 1.
RuleException:
CalledProcessError in file /mnt/shared/scratch/mmchugh/private/poppipe-update/Snakefile, line 127:
Command 'set -euo pipefail;  /mnt/shared/scratch/mmchugh/apps/conda/envs/poppipe-update/bin/python3.12 /mnt/shared/scratch/mmchugh/private/poppipe-update/.snakemake/scripts/tmpxzpqi69s.run_ska_build.py' returned non-zero exit status 1.

Error in rule ska_build:
    jobid: 15
    input: output/strains/2/rfile.txt
    output: output/strains/2/split_kmers.skf
    log: logs/ska_build_2.log (check log file(s) for error details)
    conda-env: /mnt/shared/scratch/mmchugh/private/poppipe-update/.snakemake/conda/e1bd0f462d97ca63a64059ace45578d4_
```

environment.yml was last updated 3y ago, and doesn't include eg ska2, gubbins, r-bactdating, r-transphylo. So I'm guessing there are new dependancies the pipeline needs to run?

**Comment by johnlees** [comment]
Apologies, we had updated the job environments in the `envs/` directory (which should still work with `--use-conda`) but not the top level environment file. I've now done this, so hopefully should work for you.

**Comment by martinmchugh** [comment]
Thanks for updating, this works now
